apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example1
  namespace: myexamplejob
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      parallelism: 1
      template:
        metadata:
          name: example1
        spec:
          serviceAccountName: myexamplejob
          containers:
          - name: openshift-client
            image: quay.io/anandpavithran/openshift-client:4.5.16
            command: 
            - /bin/sh
            - -c
            - oc login https://api.ocp4.example.com:6443/ -u admin -p redhat --insecure-skip-tls-verify; oc new-project test555; oc new-app --docker-image=quay.io/anandpavithran/infosys:1.0;oc expose svc infosys;sleep 30 ; oc delete project test555
          restartPolicy: OnFailure
